# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BuildTestDeploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  buildtest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      uses: actions/setup-node@v3
      with:
        node-version: '16.13'
        cache: 'npm'
    - name: install
    - run: npm ci
    - name: test
    - run: npm run test
    - name: build
    - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: buildtest

    steps:
    - name: deploy
      uses: cross-the-world/ssh-pipeline@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        connect_timeout: 10s
        script: |
          ls -la
